name: Deploy to EC2

on:
  workflow_dispatch: # 필요할 때 수동 실행
  repository_dispatch: # 서비스 레포에서 트리거
    types: [deploy]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout deploy repo
        uses: actions/checkout@v3

      - name: Docker Compose Pull & Up
        run: |
          docker-compose up -d --pull always --force-recreate
